### POST
# @no-log
POST http://127.0.0.1:3000/users
Content-Type: application/json

{
  "username": "Mario"
}

### PUT
# @no-log
PUT http://127.0.0.1:3000/users/865729
Content-Type: application/json

{
  "username": "Toad"
}

### GET all
# @no-log
GET http://127.0.0.1:3000/users

### GET by id
# @no-log
GET http://127.0.0.1:3000/users/593699

### DELETE by id
DELETE http://127.0.0.1:3000/users/257684