# @no-log

### POST
POST http://127.0.0.1:3000/users
Content-Type: application/json

{
  "username": "Mario"
}

### PUT
PUT http://127.0.0.1:3000/users/774555
Content-Type: application/json

{
  "username": "Toad"
}

### GET all
GET http://127.0.0.1:3000/users

### GET by id
GET http://127.0.0.1:3000/users/774555

### DELETE by id
DELETE http://127.0.0.1:3000/users/774555